### PR TITLE
fix: show delete prompt for delete actions

### LINKED ISSUE #399: No delete popup appears for default config
No delete popup appears for default config

### PR DESCRIPTION
**Pull request by Datron**
## Problem
Delete modal is not displayed in default config and type templates pages. Also, the type template form shows the description and change reason twice

## Solution
Show a delete prompt and remove duplicate fields

https://github.com/user-attachments/assets/d29819bf-97e1-4248-aa6c-09c13247ee8c

closes #399

### CODE REVIEW

File: crates/frontend/src/components/type_template_form.rs [hunk 1]
```diff
@@ -112,36 +112,6 @@ where
 
             </div>
 
-            <div class="form-control">
```
Comment (mahatoankitkumar) [inline crates/frontend/src/components/type_template_form.rs:115]: @Datron We don't have this description change for type_templates?

File: crates/frontend/src/pages/custom_types.rs [hunk 2]
```diff
@@ -42,6 +45,34 @@ pub fn types_page() -> impl IntoView {
                 )
         },
     );
+
+    let (delete_modal_visible_rs, delete_modal_visible_ws) = create_signal(false);
```
Comment (mahatoankitkumar) [inline crates/frontend/src/pages/custom_types.rs:49]: @Datron Don't you think this signal should be inside the DeleteModal component?

File: crates/frontend/src/pages/custom_types.rs [hunk 3]
```diff
@@ -42,6 +45,34 @@ pub fn types_page() -> impl IntoView {
...
+    let (delete_row_rs, delete_row_ws) = create_signal::<Option<TypeTemplateRow>>(None);
+
+    let confirm_delete = Callback::new(move |_| {
+        if let Some(row_data) = delete_row_rs.get().clone() {
+            spawn_local(async move {
+                let tenant = tenant_rws.get().0;
+                let org = org_rws.get().0;
+                let api_response =
+                    delete_type(tenant, row_data.clone().type_name, org).await;
+                match api_response {
```
Comment (mahatoankitkumar) [inline crates/frontend/src/pages/custom_types.rs:59]: Same for this?
And we can pass the api call function as a callback?

**Review by mahatoankitkumar — CHANGES_REQUESTED** [review]

File: crates/frontend/src/pages/custom_types.rs (hunk 3 above)
Comment (sauraww) [reply crates/frontend/src/pages/custom_types.rs:59]: Hey @Datron , both of the @mahatoankitkumar's comment make a lot of sense . We can add the show/hide method inside the component itself so that visibility state can be managed via component itself rather than being passed from the parent . Can we do these changes right now or log a ticket for the refactor which can be picked up later on ?

**Review by sauraww — CHANGES_REQUESTED** [review]

File: crates/frontend/src/components/type_template_form.rs (hunk 1 above)
Comment (Datron) [reply crates/frontend/src/components/type_template_form.rs:115]: It's there, duplicated twice. Removed one copy

File: crates/frontend/src/pages/custom_types.rs
[the remark this answers is not in the document]
Comment (Datron) [reply crates/frontend/src/pages/custom_types.rs:1]: The feature was called custom types in the beginning

File: crates/frontend/src/pages/custom_types.rs (hunk 3 above)
Comment (Datron) [reply crates/frontend/src/pages/custom_types.rs:59]: @mahatoankitkumar the API call is different for each delete right? Should the whole of the function be a callback?

File: crates/frontend/src/pages/custom_types.rs (hunk 2 above)
Comment (Datron) [reply crates/frontend/src/pages/custom_types.rs:49]: @mahatoankitkumar the modal has this inside, but since the modal is controlled by the outside page by these signals - they still need to be present right? Otherwise how do you trigger the display and hide of the modal?

File: crates/frontend/src/pages/custom_types.rs (hunk 3 above)
Comment (mahatoankitkumar) [reply crates/frontend/src/pages/custom_types.rs:59]: Yeah that can be, as rest all is common for all, and the api call would take only 3-4 lines as a callback function, rest can be common

Comment (Datron) [reply crates/frontend/src/pages/custom_types.rs:59]: The types for each function call are different, so the Callback needs to be generic. There maybe a better way to solve this.

Comment (mahatoankitkumar) [reply crates/frontend/src/pages/custom_types.rs:59]: As per our discussion, we can push this refactor for later as this might have some complexities and drawbacks.

**Review by mahatoankitkumar — APPROVED** [review]

**Review by ShreyBana — APPROVED** [review]
